### ISSUE TITLE
Documentation for website

### ISSUE THREAD

**Issue by sonam-serchan** [xplorer-io/website#4]
One pager docs where we include the details of the project. Can be within a readme or google doc or anything simple for now
## Information:
- [ ] What is it about?
- [ ] What are we building?
- [ ] Why are we building?
- [ ] What's the outcome?
- [ ] What's the value?
## Roadmap
- [ ] What's covered in MVP?
- [ ] What's coming later?
## Design process:
- [ ] Design link
## Implementation process:
- [ ] Tool used for project management
- [ ] Github repo
- [ ] Frontend stack details
- [ ] How can you contribute?

**Comment by ghimireaacs** [comment]
## Information:

- [ ]  What is it about?
	- **Xplorers Website** is a public platform for our group where we introduce ourselves, schedule events, help the community find us, and write blogs about various topics such as technology, finance, stories, personal experiences, and more. It also includes a guide to creating resumes for both beginners and advanced users.

- [ ]  What are we building?
	-  A **website** that serves as a public face for our group and a hub for our activities and content.

- [ ]  Why are we building?
	- To **increase our visibility** and engagement with the community.
	- To **share knowledge and experiences** through blogs and guides.
	- To **provide a centralized platform** for scheduling events and making connections.

- [ ]  What's the outcome?
	- A **functional website** that introduces our group, shares valuable content, and helps the community engage with us.

- [ ]  What's the value?
	- **Enhanced visibility** for our group.
	- **A resourceful platform** for the community.
	- **Opportunities for engagement** through events and blogs.
---
---


## Roadmap

- [ ]  What's covered in MVP?
	- HomePage (Learn, share and grow and a tagline) (see example [https://versent.com.au/](https://versent.com.au/))
	- About Us (Who are we? What do we do? Mission/Values?)


- [ ]  What's coming later?
	- Events Page (hackathons, meetups, zoomies, tech talks)
	- Blogs (see examples [https://versent.com.au/blog/](https://versent.com.au/blog/) [https://pentesternepal.com/blog/](https://pentesternepal.com/blog/))
	- Pathway to get a job, tips for students, how to make a great CV, success stories
	- Gallery pictures
	- Authenticated site? - to think what we can do here


``` 
😬 Nice to have:

Funny comment to user about their IP and how unprotected they are 
```
## Design process:

- [ ]  Design link
	- [Figma](https://www.figma.com/design/fQssgttgmTJNUu8mIzlxcO/Xplorers?node-id=0%3A1&t=X2JllQITmKZpZfMD-1)

## Implementation process:

- [ ]  Tool used for project management
	- MERN Stack
	
- [ ]  Github repo
	- [Github](https://github.com/xplorer-io/website)

- [ ]  Frontend stack details
	- Library - React.js
	    
	- Framework - Next.js
	    
	- CSS - Tailwind
	    
	- UI framework - ShdcnUI
	
- [ ]  How can you contribute?
	- **Immediately:**
		- Coding
		- Designing
		- Attending Weekly Meetings
	- **Later**
		- Writing Blogs
		- Maintaining Website
		- Participating on Events

> 📣  Please Join Respective Slack Channel for more Info.

**Comment by Aaasisss** [comment]
Are they supposed to be checkboxes?

**Comment by ghimireaacs** [comment]
Just for aesthetic purpose.
